--create table public.users (
--	users_id bigint NOT NULL unique PRIMARY KEY,
--	firstname varchar(100) not null,
--	lastname varchar(100) not null,
--	birthdate date not null,
--	email varchar(255) not null unique,
--	username varchar(50) not null unique,
--	password varchar(255) not null
--);